### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sankarshana16** [nebblu/ReACT#12]
![Screenshot from 2020-09-22 10-20-25](https://user-images.githubusercontent.com/52423565/93864801-5008e480-fcbd-11ea-91a7-2da968827d4a.png)
Upon running python setup.py install, I get an error about multiple definitions of some functions which causes make to fail. I have installed gcc, gsl and g++ using the standard Ubuntu apt-get install. Also, I installed Sundials 4.0.0 using the standard CMake installation as detailed in the documentation and the relevant libraries are in /usr/local/lib.  Any help would be greatly appreciated, thank you.

**Comment by nebblu** [comment]
Could you try installing sundials via brew as in https://github.com/nebblu/ReACT/issues/6 ? 

You could also try installing via "pip install ." 

Let me know if either of those works. I will try to re install it on my Ubuntu machine and see if I encounter similar errors :)

**Comment by sankarshana16** [comment]
I get the same error when I tried to install via pip...
Didn't change when I tried installing sundials via brew. Unsure what the problem is, unfortunately.

**Comment by nebblu** [comment]
Ok, so I've managed to re install on my local cluster . I had to slightly edit the pyreact/Makefile to include library and include paths for sundials (attached) and had to load GCC and GSL modules. 

One other thing you can try that has worked for other users is to work in a conda environment with something similar to

conda install -c conda-forge/label/gcc7 sundials
CFLAGS=-I$HOME/Codes/miniconda/envs/test/include CXXFLAGS=-I$HOME/Codes/miniconda/envs/test/include LDFLAGS=-L$HOME/Codes/miniconda/envs/test/lib pip install git+ssh://git@github.com/nebblu/ReACT.git@makefile#egg=pyreact

Adjust the path to your conda envs accordingly. Let me know if this works :) 

If you're new to conda: 
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands

[Makefile.txt](https://github.com/nebblu/ReACT/files/5273540/Makefile.txt)

**Comment by sankarshana16** [comment]
I changed the conda path accordingly after installing gcc7 and sundials in my conda environment, but the pip install command errored out. 
![Screenshot from 2020-09-24 13-44-22](https://user-images.githubusercontent.com/52423565/94146741-4b366300-fe6c-11ea-825d-ae896d242753.png)

**Comment by nebblu** [comment]
Could you attach the log file? 

Although it shouldn't matter,  that command was for the 'makefile' branch. Try change makefile to 'master'.

**Comment by sankarshana16** [comment]
Same error, I'm attaching the Logfile. Just so I can confirm that I understood you, you meant that I should run pip install git+ssh://git@github.com/nebblu/ReACT.git@master#egg=pyreact, right?
[LOGFILE.txt](https://github.com/nebblu/ReACT/files/5277046/LOGFILE.txt)
I'm trying to install the code on a different system (starting from scratch), to see if I messed something up along the way. Will keep you posted. Thanks very much for the help! :)

**Comment by sankarshana16** [comment]
I've fixed the problem, I re-installed Sundials, and this time I installed version 5.0 instead of 4.0. Installation worked without a hitch. :) Thanks very much for your help!

**Comment by nebblu** [comment]
Fantastic! Sorry I hadn't kept up with this issue, has been a very busy week :) Glad you figured it out anyway!
